# Generated by Django 4.2.3 on 2024-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
