# Generated by Django 4.2.3 on 2024-08-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
